### ISSUE TITLE
i need to add ionic tags to this editer 

### ISSUE THREAD

**Issue by alimuhnad** [Developer-Plexscape/ngx-grapesjs#16]
is there any way to put the ionic tags to this editer ????????

plz help me with that

**Comment by bampakoa** [comment]
Hello @alimuhnad Could you please elaborate more on what you mean when referring to **ionic tags**?

**Comment by alimuhnad** [comment]
hi there is ionicframework tags 
check this out 
https://ionicframework.com/docs/intro/cdn

now if we do it it will be super easy for us to create pages ui

**Comment by bampakoa** [comment]
So, you would like to import some Ionic framework scripts and CSS inside the editor, right?

**Comment by alimuhnad** [comment]
yes plz can we do that ? how ?

**Comment by alimuhnad** [comment]
hi any idea??
