### ISSUE TITLE
Need to access this.setup(this.webpageConfig) from component using viewchild.

### ISSUE THREAD

**Issue by prathap-reddy-shipsy** [Developer-Plexscape/ngx-grapesjs#20]
class NgxWebpageEditorComponent extends NgxEditorComponent {
    constructor() {
        super(...arguments);
        this.webpageConfig = {
            container: '#gjs',
            plugins: [
                'grapesjs-preset-webpage',
                'gjs-blocks-basic'
            ],
            pluginsOpts: {
                'grapesjs-preset-webpage': {
                    modalTitleImport: 'Import template'
                }
            }
        };
    }
    ngOnInit() {
        this.setup(this.webpageConfig);
    }
    static { this.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "16.0.2", ngImport: i0, type: NgxWebpageEditorComponent, deps: null, target: i0.ɵɵFactoryTarget.Component }); }
    static { this.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "16.0.2", type: NgxWebpageEditorComponent, selector: "ngx-grapes-webpage-editor", usesInheritance: true, ngImport: i0, template: '<div id="gjs"></div>', isInline: true }); }
}

Need to access this.setup(this.webpageConfig) from component using viewchild.

**Comment by bampakoa** [comment]
Hello there 👋 Could you please provide more details on what you are trying to achieve? Why would you need to access the `setup` method specifically?

**Comment by bampakoa** [comment]
@prathap-reddy-shipsy we are closing this issue for now. Feel free to re-open it in case you can provide more information about it. We would be very happy to hear about your case and investigate further to include it in the library 🙂
