### ISSUE TITLE
Module "ngx-grapesjs" has no exported member NgxGrapesjsModule

### ISSUE THREAD

**Issue by narimanam** [Developer-Plexscape/ngx-grapesjs#21]
Hi,
I encountered an error in the first step of adding `ngx-grapesjs`. It appears that `NgxGrapesjsModule` is missing from the `ngx-grapesjs` package. Did I overlook something?

For context, I'm using Angular version 18. Here's what I did:

1. Installed `grapesjs`.
2. Added `grapesjs-preset-webpage` and `grapesjs-blocks-basic`.
3. Used `ng add` to integrate `ngx-grapesjs` and selected the Webpage Editor option.

Any insights on what might be going wrong?

**Comment by bampakoa** [comment]
Hey there! In the latest version of the library, that is 18.0.0, we migrated to the standalone API. Which version do you use?

**Comment by bampakoa** [comment]
@GregLtrnr that's correct! It appears that the README file in the npm registry has not been updated with the correct usage described [here](https://github.com/Developer-Plexscape/ngx-grapesjs/tree/master/projects/ngx-grapesjs).

**Comment by bampakoa** [comment]
The README file in npm has been updated accordingly.
